title:            Focus on Coding
description:      A blog focus on coding written by zz.
url:              www.zzsec.org # Site url.
signoff:          zz # Your name.
disqus_shortname:   zzsec # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics:   UA-39425016-1 # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about.html
  - name:         Blog
    url:          http://www.zzsec.org
    external:     true
  - name:         Email
    url:          mailto:zz@zzsec.org
    external:     true
  - name:         GitHub
    url:          http://github.com/dieyushi
    external:     true
highlighter:      pygments
permalink:        /:year/:month/:title
exclude:
    - Rakefile
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
